// What an agent harness (or a person at a terminal) needs to write a rulebook
// outside Lumiverse: the guide, the starting templates, and the same checks the
// in-app builder runs — the loader, the linter, the balance review, the depth
// audit, encounter simulations and a preview of what the player sees first.

import { loadRuleset } from "../engine/loader.js";
import { lintRuleset } from "../engine/lint.js";
import { reviewBalance } from "../engine/balance.js";
import { auditRuleset } from "../engine/audit.js";
import { DESIGN_GUIDE, PART_CONTENTS, PART_LABELS, REFERENCE } from "../engine/reference.js";
import { joinRulebook, splitRulebook, type RulebookPart } from "../engine/rulebook.js";
import { TEMPLATES } from "../engine/templates/index.js";
import { initialState } from "../engine/state.js";
import { buildChoices, buildHud, stateDigest } from "../engine/view.js";
import { outcomeLabel } from "../engine/encounter-view.js";
import { outcomeKind, type OutcomeKind } from "../engine/outcomes.js";
import { kindsLine, patchedState, simulateEncounter as playtestEncounter, type StatePatch } from "../engine/simulate.js";
import type { Issue, Ruleset } from "../engine/ruleset.js";

export const WORKFLOW = `HOW TO WRITE A WARP RULEBOOK (with an agent harness or by hand)

Warp is a game engine that runs underneath a roleplay chat in Lumiverse. The rulebook is YAML: stats, places,
people, items, actions with dice checks, encounters, quests, statuses, perks and abilities, and the story machinery.
The engine decides outcomes; the narrator model only writes them. A good rulebook is a GAME: every piece creates a
decision, applies pressure or rewards play — and it fits the character card or setting it's for.

1. Read the card (or the brief) and name the core loop before writing YAML: what the player does most days, what
   pushes back, what they're working toward. Pick the systems that serve it (see the sections below).
2. Start from the closest template (\`warp-rulebook templates\`, then \`warp-rulebook template <id>\`) or from scratch.
   Templates are complete, balanced games — rename, retune, trim and extend rather than copying blindly.
3. Write ONE file. Either plain YAML with all top-level keys, or documents headed "--- # <section>" (that's what
   Warp's export writes). Sections: ${PART_LABELS.join(", ")}.
4. Run the checker after every meaningful change: \`warp-rulebook check rulebook.yaml\`
   - Errors: the game can't run — fix all of them.
   - Lint warnings: names that don't resolve, effects pointing at nothing — fix them.
   - Balance: odds that are hopeless or automatic, meters that run away, encounters that are unwinnable or free.
   - Depth audit: what doesn't connect (items that do nothing, stats nothing reads, quests nothing finishes…).
     Fix every [gap]; fix or knowingly accept each [thin]. Depth measures static wiring, not fun — don't chase 100
     by adding systems the game doesn't need; a narrative-only meter can be deliberate.
5. Simulate each encounter (\`warp-rulebook simulate rulebook.yaml\`): no route should be pointless, none a sure win,
   and the escape should cost something. Endings count as won / escaped / conceded / lost (mark any the engine
   misreads with \`losses:\` or \`outcome_kinds:\`). Tune numbers until random play WINS roughly 30–70% of the time —
   getting away doesn't count. For encounters met later in the game, simulate from that point:
   \`--set '{"stats":{"level":12,"hp":"max"},"flags":{"met_kael":true}}'\`.
6. Preview (\`warp-rulebook preview rulebook.yaml\`): the sidebar, choices and the narrator's view at the start.
   Check it reads well: bands in words, choices with sensible odds, quests on offer, nothing confusing.
7. Hand the file over. In Lumiverse: Warp → Ruleset → Import a rulebook (paste or choose the file) → review → Install.
   It lands in the character's "warp-ruleset" lorebook, one entry per section, and can be refined there later.

Rules of thumb: snake_case ids; meters 0–100 unless there's a reason; quote formulas that contain commas;
in-world text in the card's voice; refer to the player as {{user}}. Never anything sexual involving anyone under 18 —
Warp refuses to run a rulebook that declares minors alongside sexual actions.`;

/** The whole authoring guide: workflow, what goes in each section, the format reference and the design guide. */
export function guideText(section: "all" | "workflow" | "format" | "design" = "all"): string {
  const sections = `SECTIONS (each becomes one lorebook entry, "warp-ruleset · <section>"):\n${PART_LABELS.map((l) => `- ${l}: ${PART_CONTENTS[l]}`).join("\n")}`;
  if (section === "workflow") return `${WORKFLOW}\n\n${sections}`;
  if (section === "format") return REFERENCE;
  if (section === "design") return DESIGN_GUIDE;
  return [WORKFLOW, sections, REFERENCE, DESIGN_GUIDE].join("\n\n");
}

/** The guide as Markdown, for docs/RULEBOOK_GUIDE.md (regenerated by `warp-rulebook guide --markdown`). */
export function guideMarkdown(): string {
  return [
    "# Writing a Warp rulebook",
    "",
    "<!-- Generated from src/engine/reference.ts and src/tools/rulebook-tools.ts by `bun run guide`. Don't edit by hand. -->",
    "",
    "This guide is for writing a rulebook **outside Lumiverse** — by hand, or with an agent harness (Claude Code, Codex, Cursor, Aider…) that can run the checker. Building in Lumiverse (Warp → Ruleset → Build with AI) uses the same format and the same checks.",
    "",
    "## Tools",
    "",
    "```bash",
    "node dist/warp-rulebook.js guide            # this guide, as plain text",
    "node dist/warp-rulebook.js templates        # the starting templates",
    "node dist/warp-rulebook.js template questbound > rulebook.yaml",
    "node dist/warp-rulebook.js check rulebook.yaml",
    "node dist/warp-rulebook.js simulate rulebook.yaml",
    "node dist/warp-rulebook.js preview rulebook.yaml",
    "node dist/warp-rulebook.js mcp              # the same, as an MCP server over stdio",
    "```",
    "",
    "Without cloning: `npx -y github:japolino/warp check rulebook.yaml`. As an MCP server (Claude Code: `claude mcp add warp -- npx -y github:japolino/warp mcp`) it offers `warp_guide`, `warp_templates`, `warp_template`, `warp_check`, `warp_simulate` and `warp_preview`.",
    "",
    "## Workflow",
    "",
    "```text",
    WORKFLOW,
    "```",
    "",
    "## Sections",
    "",
    ...PART_LABELS.map((l) => `- **${l}** — ${PART_CONTENTS[l]}`),
    "",
    "## Format reference",
    "",
    "```yaml",
    REFERENCE.trim(),
    "```",
    "",
    "## Design guide",
    "",
    DESIGN_GUIDE.trim().replace(/^## /gm, "### ").replace(/^WARP DESIGN GUIDE — /, "**Warp design guide —** "),
    "",
  ].join("\n");
}

export function templateList(): string {
  return TEMPLATES.map((t) => `${t.id} — ${t.name}\n  ${t.blurb}`).join("\n\n");
}

export function templateText(id: string): string | null {
  const t = TEMPLATES.find((x) => x.id === id);
  return t ? joinRulebook(t.parts, t.name) : null;
}

/** Load a rulebook from one file's text (or several, merged in order). */
export function loadText(texts: string[]): { parts: RulebookPart[]; ruleset: Ruleset | null; issues: Issue[] } {
  const parts = texts.flatMap((t) => splitRulebook(t));
  const { ruleset, issues } = loadRuleset(parts.map((p, i) => ({ label: `warp-ruleset · ${p.label}`, content: p.yaml, order: i })));
  return { parts, ruleset, issues: ruleset ? [...issues, ...lintRuleset(ruleset)] : issues };
}

export interface CheckReport {
  ok: boolean;
  name: string | null;
  sections: string[];
  errors: Issue[];
  warnings: Issue[];
  balance: { id: string; part: string; text: string; fix: string }[];
  depth: number | null;
  gaps: { id: string; severity: string; part: string; text: string; fix: string }[];
  contents: Record<string, number>;
}

export function checkReport(texts: string[]): CheckReport {
  const { parts, ruleset: r, issues } = loadText(texts);
  const errors = issues.filter((i) => i.level === "error");
  const warnings = issues.filter((i) => i.level === "warning");
  const audit = r ? auditRuleset(r) : null;
  return {
    ok: !!r && !errors.length,
    name: r?.name ?? null,
    sections: parts.map((p) => p.label),
    errors, warnings,
    balance: r ? reviewBalance(r) : [],
    depth: audit?.depth ?? null,
    gaps: audit?.gaps ?? [],
    contents: r ? {
      stats: r.statOrder.length, people: Object.keys(r.people).length, places: Object.keys(r.locations).length,
      items: Object.keys(r.items).length, actions: Object.keys(r.actions).length, encounters: Object.keys(r.encounters).length,
      quests: r.questOrder.length, conditions: Object.keys(r.conditions).length, abilities: Object.keys(r.abilities).length,
      perks: Object.keys(r.perks).length, triggers: r.triggers.length, codex: Object.keys(r.codex).length,
    } : {},
  };
}

export function checkText(rep: CheckReport): string {
  const out: string[] = [];
  out.push(`WARP RULEBOOK CHECK — ${rep.name ?? "(doesn't load)"}`);
  out.push(`Sections: ${rep.sections.join(", ") || "none found"}`);
  const has = Object.entries(rep.contents).filter(([, n]) => n).map(([k, n]) => `${n} ${k}`).join(", ");
  if (has) out.push(`Contains: ${has}`);
  out.push("");
  if (rep.errors.length) {
    out.push(`✕ ERRORS (${rep.errors.length}) — the game can't run until these are fixed:`);
    for (const i of rep.errors) out.push(`  - ${i.where}: ${i.message}`);
    out.push("");
  }
  if (rep.warnings.length) {
    out.push(`! WARNINGS (${rep.warnings.length}) — names that don't resolve, effects that point at nothing:`);
    for (const i of rep.warnings) out.push(`  - ${i.where}: ${i.message}`);
    out.push("");
  }
  if (rep.balance.length) {
    out.push(`⚖ BALANCE (${rep.balance.length}):`);
    for (const b of rep.balance) out.push(`  - [${b.part}] ${b.text}\n      fix: ${b.fix}`);
    out.push("");
  }
  if (rep.depth !== null) {
    const gaps = rep.gaps.filter((g) => g.severity === "gap");
    const thin = rep.gaps.filter((g) => g.severity !== "gap");
    out.push(`◆ DEPTH ${rep.depth}/100 — ${gaps.length} gap${gaps.length === 1 ? "" : "s"}, ${thin.length} thin spot${thin.length === 1 ? "" : "s"}`);
    for (const g of [...gaps, ...thin]) out.push(`  - [${g.severity}] (${g.part}) ${g.text}\n      fix: ${g.fix}`);
    out.push("");
  }
  out.push(rep.ok
    ? rep.warnings.length || rep.balance.length || rep.gaps.some((g) => g.severity === "gap")
      ? "Runs. Work through the list above, then simulate the encounters."
      : "✓ Clean: runs, lints clean, no balance problems, no gaps. Simulate the encounters and preview it, then import it in Warp."
    : "✕ Doesn't run yet — fix the errors first.");
  return out.join("\n");
}

export interface SimulateOptions {
  /** Simulate from the start with these changes (a level, gear, flags, a place…), after triggers run. Overrides each encounter's own `sim:`. */
  set?: StatePatch;
  /** Also play each "always the same move" strategy (default true). */
  strategies?: boolean;
}

/** A state patch from `--set <json>` and `--stat id=value` flags (or an MCP `set` / `stats` argument). */
export function readPatch(set: unknown, stats: string[] = []): StatePatch | undefined {
  let patch: StatePatch | undefined;
  if (typeof set === "string" && set.trim()) {
    try { patch = JSON.parse(set) as StatePatch; } catch { throw new Error(`--set needs JSON, like '{"stats":{"level":12}}' (got ${set})`); }
  } else if (set && typeof set === "object") patch = set as StatePatch;
  if (patch !== undefined && (typeof patch !== "object" || Array.isArray(patch))) throw new Error("set must be an object: { stats, flags, items, location, conditions, rel, perks, wear }");
  for (const kv of stats) {
    const m = /^([a-z_]\w*)\s*=\s*(.+)$/i.exec(kv.trim());
    if (!m) throw new Error(`--stat needs id=value (got "${kv}")`);
    patch = { ...(patch ?? {}), stats: { ...(patch?.stats ?? {}), [m[1]]: /^(max|min)$/i.test(m[2]) ? m[2] : Number(m[2]) } };
  }
  return patch;
}

const KIND_MARK: Record<OutcomeKind, string> = { won: "(won)", escaped: "(escaped)", conceded: "(conceded)", lost: "(loss)" };

/** Describe a patch in one line ("level 12, hp max, flag met_kael…"). */
function patchText(p: StatePatch): string {
  const bits: string[] = [];
  for (const [k, v] of Object.entries(p.stats ?? {})) bits.push(`${k} ${v}`);
  for (const [k, v] of Object.entries(p.flags ?? {})) bits.push(`flag ${k}=${JSON.stringify(v)}`);
  for (const [k, v] of Object.entries(p.items ?? {})) bits.push(`${k} ×${v}`);
  if (p.location) bits.push(`at ${p.location}`);
  const conds = Array.isArray(p.conditions) ? p.conditions : Object.keys(p.conditions ?? {});
  if (conds.length) bits.push(`status ${conds.join(", ")}`);
  for (const [who, m] of Object.entries(p.rel ?? {})) for (const [k, v] of Object.entries(m ?? {})) bits.push(`${who}.${k} ${v}`);
  if (p.perks?.length) bits.push(`perks ${p.perks.join(", ")}`);
  const worn = Array.isArray(p.wear) ? p.wear : Object.values(p.wear ?? {});
  if (worn.length) bits.push(`wearing ${worn.join(", ")}`);
  return bits.join(", ") || "no changes";
}

/**
 * Play through each encounter from the starting state (or a patched one): random play, how it tends to end,
 * and how each "always the same move" strategy fares. Endings count as won / escaped / conceded / lost —
 * the same classifier the checker and quest goals use. "Ends well" = anything but lost; the checker's
 * balance target judges wins, so a fight everyone flees from doesn't pass as balanced.
 */
export function simulateText(texts: string[], only?: string, runs = 200, opts: SimulateOptions = {}): string {
  const { ruleset: r, issues } = loadText(texts);
  if (!r) return `The rulebook doesn't load:\n${issues.filter((i) => i.level === "error").map((i) => `  - ${i.where}: ${i.message}`).join("\n")}`;
  const ids = only ? [only] : Object.keys(r.encounters);
  if (!ids.length) return "No encounters to simulate.";
  let start = initialState(r);
  const head: string[] = [];
  if (opts.set) {
    const { state, notes } = patchedState(r, opts.set, start);
    if (state.encounter) { notes.push(`a trigger started "${state.encounter.id}" — simulating from just before it`); state.encounter = null; }
    start = state;
    head.push(`From the start with: ${patchText(opts.set)} (then triggers ran).`);
    for (const n of notes) head.push(`  ! ${n}`);
  }
  const out: string[] = [
    `Random play from the ${opts.set ? "patched" : "starting"} state, ${runs} runs each (a player who picks any available move):`,
    ...head,
    `Endings count as won / escaped / conceded / lost; "ends well" = anything but lost. The checker judges wins.`, "",
  ];
  for (const id of ids) {
    const enc = r.encounters[id];
    if (!enc) { out.push(`${id}: no such encounter (${Object.keys(r.encounters).join(", ")})`); continue; }
    // The encounter's own sim: (its intended point in the game) unless a patch was passed in.
    let from = start;
    if (!opts.set && enc.sim) {
      const p = patchedState(r, enc.sim, start);
      from = p.state;
      from.encounter = null;
      out.push(`${enc.name}: judged from its sim: ${patchText(enc.sim)}${p.notes.length ? ` (! ${p.notes.join("; ")})` : ""}`);
    }
    const sim = playtestEncounter(r, id, { from, runs, maxRounds: 25, randomOnly: opts.strategies === false });
    const random = sim?.policies.find((p) => p.policy === "a random mix");
    if (!sim || !random) continue;
    const rows = Object.entries(random.outcomes).sort((a, b) => b[1] - a[1])
      .map(([o, n]) => `    ${String(Math.round((n / runs) * 100)).padStart(3)}%  ${outcomeLabel(enc, o)}  ${KIND_MARK[outcomeKind(enc, o)]}`);
    const k = random.kinds;
    const well = k.won + k.escaped + k.conceded;
    out.push(`${enc.name} (${id}) — ends well ${Math.round((well / runs) * 100)}% (${kindsLine(k, runs)}), about ${(random.meanRounds ?? random.medianRounds).toFixed(1)} rounds`);
    out.push(...rows);
    if (random.unfinished) out.push(`    ${String(Math.round((random.unfinished / runs) * 100)).padStart(3)}%  still going after 25 rounds`);
    const fixed = sim.policies.filter((p) => p !== random);
    if (fixed.length) {
      out.push("  By strategy (the same move every round, when it's offered):");
      for (const p of fixed) out.push(`    ${p.policy}: ${kindsLine(p.kinds, p.runs, p.unfinished)} · median ${p.medianRounds} rounds`);
    }
    for (const n of sim.notes) out.push(`  note: ${n}`);
    out.push("");
  }
  return out.join("\n").trim();
}

/** What the player sees at the start (sidebar and choices), and what the narrator is told. */
export function previewText(texts: string[]): string {
  const { ruleset: r, issues } = loadText(texts);
  if (!r) return `The rulebook doesn't load:\n${issues.filter((i) => i.level === "error").map((i) => `  - ${i.where}: ${i.message}`).join("\n")}`;
  const s = initialState(r);
  const hud = buildHud(r, s);
  const out: string[] = [`${r.name}${r.description ? ` — ${r.description}` : ""}`, ""];
  out.push("SIDEBAR AT THE START");
  if (hud.clock) out.push(`  ${hud.date ?? hud.clock.day}, ${hud.clock.time}`);
  if (hud.location) out.push(`  📍 ${hud.location.name}${hud.money ? `  ·  ${hud.money}` : ""}`);
  for (const b of hud.bars) out.push(`  ${b.label}: ${b.text ? `${b.text} (${b.display})` : b.display}`);
  if (hud.skills.length) out.push(`  Skills: ${hud.skills.map((x) => `${x.label} ${x.grade ?? x.text ?? x.display}`).join(", ")}`);  // same as the sidebar
  const pools = new Map<string, { label: string; left: number; stats: string[] }>();
  for (const x of hud.skills) if (x.allocate) {
    const p = pools.get(x.allocate.pool) ?? { label: x.allocate.poolLabel, left: x.allocate.left, stats: [] };
    p.stats.push(x.label);
    pools.set(x.allocate.pool, p);
  }
  for (const p of pools.values()) out.push(`  Spend ${p.label} (${p.left} now) with + beside: ${p.stats.join(", ")} — a sheet change, no story turn`);
  if (hud.items.length) out.push(`  Carrying: ${hud.items.map((i) => `${i.name}${i.count > 1 ? ` ×${i.count}` : ""}${i.use ? ` [${i.use.label}]` : ""}${i.bonus ? ` (${i.bonus})` : ""}`).join(", ")}`);
  if (hud.abilities.length) out.push(`  Abilities: ${hud.abilities.map((a) => `${a.name}${a.cost ? ` (${a.cost})` : ""}`).join(", ")}`);
  for (const q of hud.quests) out.push(`  Quest (${q.status}): ${q.name}${q.from ? ` — ${q.from}` : ""}${q.reward ? ` · reward ${q.reward}` : ""}${q.stakes ? ` · ${q.stakes}` : ""}`);
  out.push("", "CHOICES AT THE START");
  for (const c of buildChoices(r, s, { lines: [], veils: [] })) {
    out.push(`  [${c.group ?? "Actions"}] ${c.label}${c.odds !== null ? ` — ${Math.round(c.odds * 100)}%${c.checkLabel ? ` ${c.checkLabel}` : ""}` : ""}${c.locked ? ` — 🔒 ${c.locked}` : ""}${c.why ? ` — ${c.why}` : ""}`);
  }
  out.push("", "WHAT THE NARRATOR IS TOLD (a turn that names nothing in particular; items, skills, quests and the board join only when a turn brings them up)", ...stateDigest(r, s, { text: "" }).split("\n").map((l) => `  ${l}`));
  return out.join("\n");
}
