// What an agent harness (or a person at a terminal) needs to write a rulebook
// outside Lumiverse: the guide, the starting templates, and the same checks the
// in-app builder runs — the loader, the linter, the balance review, the depth
// audit, encounter simulations and a preview of what the player sees first.

import { loadRuleset } from "../engine/loader.js";
import { lintRuleset } from "../engine/lint.js";
import { reviewBalance, simulateEncounter } from "../engine/balance.js";
import { auditRuleset } from "../engine/audit.js";
import { DESIGN_GUIDE, PART_CONTENTS, PART_LABELS, REFERENCE } from "../engine/reference.js";
import { joinRulebook, splitRulebook, type RulebookPart } from "../engine/rulebook.js";
import { TEMPLATES } from "../engine/templates/index.js";
import { initialState } from "../engine/state.js";
import { buildChoices, buildHud, stateDigest } from "../engine/view.js";
import { isLoss, outcomeLabel } from "../engine/encounter-view.js";
import type { Issue, Ruleset } from "../engine/ruleset.js";

export const WORKFLOW = `HOW TO WRITE A WARP RULEBOOK (with an agent harness or by hand)

Warp is a game engine that runs underneath a roleplay chat in Lumiverse. The rulebook is YAML: stats, places,
people, items, actions with dice checks, encounters, quests, statuses, perks and abilities, and the story machinery.
The engine decides outcomes; the narrator model only writes them. A good rulebook is a GAME: every piece creates a
decision, applies pressure or rewards play — and it fits the character card or setting it's for.

1. Read the card (or the brief) and name the core loop before writing YAML: what the player does most days, what
   pushes back, what they're working toward. Pick the systems that serve it (see the sections below).
2. Start from the closest template (\`warp-rulebook templates\`, then \`warp-rulebook template <id>\`) or from scratch.
   Templates are complete, balanced games — rename, retune, trim and extend rather than copying blindly.
3. Write ONE file. Either plain YAML with all top-level keys, or documents headed "--- # <section>" (that's what
   Warp's export writes). Sections: ${PART_LABELS.join(", ")}.
4. Run the checker after every meaningful change: \`warp-rulebook check rulebook.yaml\`
   - Errors: the game can't run — fix all of them.
   - Lint warnings: names that don't resolve, effects pointing at nothing — fix them.
   - Balance: odds that are hopeless or automatic, meters that run away, encounters that are unwinnable or free.
   - Depth audit: what doesn't connect (items that do nothing, stats nothing reads, quests nothing finishes…).
     Fix every [gap]; fix or knowingly accept each [thin]. Depth measures static wiring, not fun — don't chase 100
     by adding systems the game doesn't need; a narrative-only meter can be deliberate.
5. Simulate each encounter (\`warp-rulebook simulate rulebook.yaml\`): no route should be pointless, none a sure win,
   and the escape should cost something. Tune numbers until random play wins roughly 30–70% of the time.
6. Preview (\`warp-rulebook preview rulebook.yaml\`): the sidebar, choices and the narrator's view at the start.
   Check it reads well: bands in words, choices with sensible odds, quests on offer, nothing confusing.
7. Hand the file over. In Lumiverse: Warp → Ruleset → Import a rulebook (paste or choose the file) → review → Install.
   It lands in the character's "warp-ruleset" lorebook, one entry per section, and can be refined there later.

Rules of thumb: snake_case ids; meters 0–100 unless there's a reason; quote formulas that contain commas;
in-world text in the card's voice; refer to the player as {{user}}. Never anything sexual involving anyone under 18 —
Warp refuses to run a rulebook that declares minors alongside sexual actions.`;

/** The whole authoring guide: workflow, what goes in each section, the format reference and the design guide. */
export function guideText(section: "all" | "workflow" | "format" | "design" = "all"): string {
  const sections = `SECTIONS (each becomes one lorebook entry, "warp-ruleset · <section>"):\n${PART_LABELS.map((l) => `- ${l}: ${PART_CONTENTS[l]}`).join("\n")}`;
  if (section === "workflow") return `${WORKFLOW}\n\n${sections}`;
  if (section === "format") return REFERENCE;
  if (section === "design") return DESIGN_GUIDE;
  return [WORKFLOW, sections, REFERENCE, DESIGN_GUIDE].join("\n\n");
}

/** The guide as Markdown, for docs/RULEBOOK_GUIDE.md (regenerated by `warp-rulebook guide --markdown`). */
export function guideMarkdown(): string {
  return [
    "# Writing a Warp rulebook",
    "",
    "<!-- Generated from src/engine/reference.ts and src/tools/rulebook-tools.ts by `bun run guide`. Don't edit by hand. -->",
    "",
    "This guide is for writing a rulebook **outside Lumiverse** — by hand, or with an agent harness (Claude Code, Codex, Cursor, Aider…) that can run the checker. Building in Lumiverse (Warp → Ruleset → Build with AI) uses the same format and the same checks.",
    "",
    "## Tools",
    "",
    "```bash",
    "node dist/warp-rulebook.js guide            # this guide, as plain text",
    "node dist/warp-rulebook.js templates        # the starting templates",
    "node dist/warp-rulebook.js template questbound > rulebook.yaml",
    "node dist/warp-rulebook.js check rulebook.yaml",
    "node dist/warp-rulebook.js simulate rulebook.yaml",
    "node dist/warp-rulebook.js preview rulebook.yaml",
    "node dist/warp-rulebook.js mcp              # the same, as an MCP server over stdio",
    "```",
    "",
    "Without cloning: `npx -y github:japolino/warp check rulebook.yaml`. As an MCP server (Claude Code: `claude mcp add warp -- npx -y github:japolino/warp mcp`) it offers `warp_guide`, `warp_templates`, `warp_template`, `warp_check`, `warp_simulate` and `warp_preview`.",
    "",
    "## Workflow",
    "",
    "```text",
    WORKFLOW,
    "```",
    "",
    "## Sections",
    "",
    ...PART_LABELS.map((l) => `- **${l}** — ${PART_CONTENTS[l]}`),
    "",
    "## Format reference",
    "",
    "```yaml",
    REFERENCE.trim(),
    "```",
    "",
    "## Design guide",
    "",
    DESIGN_GUIDE.trim().replace(/^## /gm, "### ").replace(/^WARP DESIGN GUIDE — /, "**Warp design guide —** "),
    "",
  ].join("\n");
}

export function templateList(): string {
  return TEMPLATES.map((t) => `${t.id} — ${t.name}\n  ${t.blurb}`).join("\n\n");
}

export function templateText(id: string): string | null {
  const t = TEMPLATES.find((x) => x.id === id);
  return t ? joinRulebook(t.parts, t.name) : null;
}

/** Load a rulebook from one file's text (or several, merged in order). */
export function loadText(texts: string[]): { parts: RulebookPart[]; ruleset: Ruleset | null; issues: Issue[] } {
  const parts = texts.flatMap((t) => splitRulebook(t));
  const { ruleset, issues } = loadRuleset(parts.map((p, i) => ({ label: `warp-ruleset · ${p.label}`, content: p.yaml, order: i })));
  return { parts, ruleset, issues: ruleset ? [...issues, ...lintRuleset(ruleset)] : issues };
}

export interface CheckReport {
  ok: boolean;
  name: string | null;
  sections: string[];
  errors: Issue[];
  warnings: Issue[];
  balance: { id: string; part: string; text: string; fix: string }[];
  depth: number | null;
  gaps: { id: string; severity: string; part: string; text: string; fix: string }[];
  contents: Record<string, number>;
}

export function checkReport(texts: string[]): CheckReport {
  const { parts, ruleset: r, issues } = loadText(texts);
  const errors = issues.filter((i) => i.level === "error");
  const warnings = issues.filter((i) => i.level === "warning");
  const audit = r ? auditRuleset(r) : null;
  return {
    ok: !!r && !errors.length,
    name: r?.name ?? null,
    sections: parts.map((p) => p.label),
    errors, warnings,
    balance: r ? reviewBalance(r) : [],
    depth: audit?.depth ?? null,
    gaps: audit?.gaps ?? [],
    contents: r ? {
      stats: r.statOrder.length, people: Object.keys(r.people).length, places: Object.keys(r.locations).length,
      items: Object.keys(r.items).length, actions: Object.keys(r.actions).length, encounters: Object.keys(r.encounters).length,
      quests: r.questOrder.length, conditions: Object.keys(r.conditions).length, abilities: Object.keys(r.abilities).length,
      perks: Object.keys(r.perks).length, triggers: r.triggers.length, codex: Object.keys(r.codex).length,
    } : {},
  };
}

export function checkText(rep: CheckReport): string {
  const out: string[] = [];
  out.push(`WARP RULEBOOK CHECK — ${rep.name ?? "(doesn't load)"}`);
  out.push(`Sections: ${rep.sections.join(", ") || "none found"}`);
  const has = Object.entries(rep.contents).filter(([, n]) => n).map(([k, n]) => `${n} ${k}`).join(", ");
  if (has) out.push(`Contains: ${has}`);
  out.push("");
  if (rep.errors.length) {
    out.push(`✕ ERRORS (${rep.errors.length}) — the game can't run until these are fixed:`);
    for (const i of rep.errors) out.push(`  - ${i.where}: ${i.message}`);
    out.push("");
  }
  if (rep.warnings.length) {
    out.push(`! WARNINGS (${rep.warnings.length}) — names that don't resolve, effects that point at nothing:`);
    for (const i of rep.warnings) out.push(`  - ${i.where}: ${i.message}`);
    out.push("");
  }
  if (rep.balance.length) {
    out.push(`⚖ BALANCE (${rep.balance.length}):`);
    for (const b of rep.balance) out.push(`  - [${b.part}] ${b.text}\n      fix: ${b.fix}`);
    out.push("");
  }
  if (rep.depth !== null) {
    const gaps = rep.gaps.filter((g) => g.severity === "gap");
    const thin = rep.gaps.filter((g) => g.severity !== "gap");
    out.push(`◆ DEPTH ${rep.depth}/100 — ${gaps.length} gap${gaps.length === 1 ? "" : "s"}, ${thin.length} thin spot${thin.length === 1 ? "" : "s"}`);
    for (const g of [...gaps, ...thin]) out.push(`  - [${g.severity}] (${g.part}) ${g.text}\n      fix: ${g.fix}`);
    out.push("");
  }
  out.push(rep.ok
    ? rep.warnings.length || rep.balance.length || rep.gaps.some((g) => g.severity === "gap")
      ? "Runs. Work through the list above, then simulate the encounters."
      : "✓ Clean: runs, lints clean, no balance problems, no gaps. Simulate the encounters and preview it, then import it in Warp."
    : "✕ Doesn't run yet — fix the errors first.");
  return out.join("\n");
}

/** Random play through each encounter from the starting state: how it tends to end, and how long it takes. */
export function simulateText(texts: string[], only?: string, runs = 200): string {
  const { ruleset: r, issues } = loadText(texts);
  if (!r) return `The rulebook doesn't load:\n${issues.filter((i) => i.level === "error").map((i) => `  - ${i.where}: ${i.message}`).join("\n")}`;
  const ids = only ? [only] : Object.keys(r.encounters);
  if (!ids.length) return "No encounters to simulate.";
  const start = initialState(r);
  const out: string[] = [`Random play from the starting state, ${runs} runs each (a player who picks any available move):`, ""];
  for (const id of ids) {
    const enc = r.encounters[id];
    if (!enc) { out.push(`${id}: no such encounter (${Object.keys(r.encounters).join(", ")})`); continue; }
    const sim = simulateEncounter(r, start, id, runs);
    if (!sim) continue;
    const rows = Object.entries(sim.outcomes).sort((a, b) => b[1] - a[1])
      .map(([o, n]) => `    ${String(Math.round((n / runs) * 100)).padStart(3)}%  ${outcomeLabel(enc, o)}${isLoss(enc, o) ? "  (loss)" : ""}`);
    const won = Object.entries(sim.outcomes).filter(([o]) => !isLoss(enc, o)).reduce((n, [, x]) => n + x, 0);
    out.push(`${enc.name} (${id}) — ends well ${Math.round((won / runs) * 100)}%, about ${sim.rounds.toFixed(1)} rounds`);
    out.push(...rows);
    if (sim.stuck) out.push(`    ${String(Math.round((sim.stuck / runs) * 100)).padStart(3)}%  still going after 25 rounds`);
    out.push("");
  }
  return out.join("\n").trim();
}

/** What the player sees at the start (sidebar and choices), and what the narrator is told. */
export function previewText(texts: string[]): string {
  const { ruleset: r, issues } = loadText(texts);
  if (!r) return `The rulebook doesn't load:\n${issues.filter((i) => i.level === "error").map((i) => `  - ${i.where}: ${i.message}`).join("\n")}`;
  const s = initialState(r);
  const hud = buildHud(r, s);
  const out: string[] = [`${r.name}${r.description ? ` — ${r.description}` : ""}`, ""];
  out.push("SIDEBAR AT THE START");
  if (hud.clock) out.push(`  ${hud.date ?? hud.clock.day}, ${hud.clock.time}`);
  if (hud.location) out.push(`  📍 ${hud.location.name}${hud.money ? `  ·  ${hud.money}` : ""}`);
  for (const b of hud.bars) out.push(`  ${b.label}: ${b.text ? `${b.text} (${b.display})` : b.display}`);
  if (hud.skills.length) out.push(`  Skills: ${hud.skills.map((x) => `${x.label} ${x.grade ?? x.display}`).join(", ")}`);
  if (hud.items.length) out.push(`  Carrying: ${hud.items.map((i) => `${i.name}${i.count > 1 ? ` ×${i.count}` : ""}${i.use ? ` [${i.use.label}]` : ""}${i.bonus ? ` (${i.bonus})` : ""}`).join(", ")}`);
  if (hud.abilities.length) out.push(`  Abilities: ${hud.abilities.map((a) => `${a.name}${a.cost ? ` (${a.cost})` : ""}`).join(", ")}`);
  for (const q of hud.quests) out.push(`  Quest (${q.status}): ${q.name}${q.from ? ` — ${q.from}` : ""}${q.reward ? ` · reward ${q.reward}` : ""}${q.stakes ? ` · ${q.stakes}` : ""}`);
  out.push("", "CHOICES AT THE START");
  for (const c of buildChoices(r, s, { lines: [], veils: [] })) {
    out.push(`  [${c.group ?? "Actions"}] ${c.label}${c.odds !== null ? ` — ${Math.round(c.odds * 100)}%${c.checkLabel ? ` ${c.checkLabel}` : ""}` : ""}${c.locked ? ` — 🔒 ${c.locked}` : ""}${c.why ? ` — ${c.why}` : ""}`);
  }
  out.push("", "WHAT THE NARRATOR IS TOLD", ...stateDigest(r, s).split("\n").map((l) => `  ${l}`));
  return out.join("\n");
}
